# Generated by Django 4.1.3 on 2022-11-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityofnewyourk', '0002_building_appt_block_building_appt_boro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='attorney_group_old',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='protest_old',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
